### ISSUE TITLE
Shift+Tab

### ISSUE THREAD

**Issue by feinstein** [blintend/tabinta#3]
I use the <kbd>Shift</kbd>+<kbd>Tab</kbd> a lot to remove indent from code. While the  <kbd>Tab</kbd> works fine in this extension, the <kbd>Shift</kbd>+<kbd>Tab</kbd> moves the focus to the previous place.

Could you please add the same behavior of <kbd>Tab</kbd> to the the <kbd>Shift</kbd>+<kbd>Tab</kbd>?

Thanks!

**Comment by blintend** [comment]
This addon is really only for entering the tab character. Obviously, html text areas lack many common text editing features but there are other addons that globally enhance/replace of text areas, e.g. [It's All Text!](https://addons.mozilla.org/en-US/firefox/addon/its-all-text/) - please consider those for advanced text editing.

**Comment by feinstein** [comment]
Wel...I don't understand why you think a <kbd>Shift</kbd>+<kbd>Tab</kbd> is not a kind of <kbd>Tab</kbd>, but I respect your opinion. 

I don't like that other extension, it will pollute my browser too much.
