### ISSUE TITLE
Example provided is a dead link

### ISSUE THREAD

**Issue by MikeKostich** [blintend/tabinta#4]
Hi, I downloaded your add-in and was trying (unsuccessfully) to see if it would work for me, at this page

https://addons.mozilla.org/en-US/firefox/addon/tabinta/reviews/349638/

and the example given is unavailable.
http://c2.com/cgi/wiki?edit=WikiWikiSandbox

Anyway, here's why I would like to be able to insert tabs, nothing at all to do with coding:

http://community.techwhirl.com/discussion/1330/is-there-a-java-applet-or-other-tool-to-insert-tabs-into-a-row-of-text#latest

Anyway, it could be a potential user group you're unaware of.

Thanks, best of luck

Mike K.

**Comment by blintend** [comment]
Hi Mike,
Here is a working page where you can try it out: https://developer.mozilla.org/de/docs/Web/HTML/Element/textarea#Example

**Comment by MikeKostich** [comment]
Hi, 

Thanks for your help and quick reply. Page works and I copied my text into the window but realized
I'm not sure how it works...... Seems as though the add-on is active ---- when I right-click in the 
text field I pasted into that window, I see the  tabinta option checked.

But anyway, here's what I'm trying to do...... I have text strings, like this --- this is one I started but haven't finished.

To insert tabs in the appropirate places, to create tables in Word, I have to use two hands, quickly,
over and over..... click  the cursor where I want the tab to be, with right hand, and hit the tab key
with my left....... I'm trying to speed up that process. I know that many hardware tech writers, like
me, have to use this technique to create tab delimited text from pdf's......

Example:

1    1    CAP ELEVATOR/SORTER    115270
2    1    LOWER CAP APPLIER ASM     175089
3     1     LEG BRACE WLD, WATERFALL     174149
4     1     AIR MANIFOLD ASM     174139
5     2     KNOB WELDMENT, 3/8-16     176023
6     1     CORNER MOUNT WLD     176069
7     4     HANDLE, RATCHET     54943
8     1     CHUTE COVER MNTG BRKT     176027
9    1     CHUTE COVER MNTG BRKT     176075
10     1     CHUTE COVER MNTG BRKT     176077
11     1     CHUTE COVER MNTG BRKT     176078
12     1     CHUTE COVER MNTG BRKT     176079
13     1     CHUTE COVER MNTG BRKT     176084
14     1     CHUTE COVER MNTG BRKT     176085
15     1     CHUTE COVER MNTG BRKT     176086
16     1 CHUTE COVER MNTG BRKT 176128
17 1 CHUTE COVER MNTG BRKT 176094
18 1 CHUTE COVER MNTG BRKT 176102
19 1 UPPER CAP CHUTE ASM 176088
20 1 UPPER CAP CHUTE COVER WLD 176092

Appreciate your help,

Mike K.

-----Original Message-----

**Comment by blintend** [comment]
The tabinta addon is for those who regularly type texts in the Firefox browser. If you do your work in Word, this may not be suitable for you. Also, tabinta can insert just a single tab at a time, not mass-convert spaces to tabs with a single click.

In Word, you can find/replace spaces (or anything) with tabs, see an explanation e.g. here: https://support.office.com/en-us/article/Find-and-replace-text-and-other-data-in-a-Word-document-c6728c16-469e-43cd-afe4-7708c6c779b7#__toc282774575

**Comment by MikeKostich** [comment]
Thanks, I know find & replace. Problem  is number  of space characters  never the same...I was afraid  only a developer tool but had to chk. Have a good one and thanks again.

Sent from my T-Mobile 4G LTE Device-------- Original message --------From: blintend notifications@github.com Date: 3/7/2016  2:57 PM  (GMT-06:00) To: blintend/tabinta tabinta@noreply.github.com Cc: MikeKostich mihailokostich@aim.com Subject: Re: [tabinta] Example provided is a dead link (#4) 
The tabinta addon is for those who regularly type texts in the Firefox browser. If you do your work in Word, this may not be suitable for you. Also, tabinta can insert just a single tab at a time, not mass-convert spaces to tabs with a single click.

In Word, you can find/replace spaces (or anything) with tabs, see an explanation e.g. here: https://support.office.com/en-us/article/Find-and-replace-text-and-other-data-in-a-Word-document-c6728c16-469e-43cd-afe4-7708c6c779b7#__toc282774575
